version: "3.0"

# Services to run
services:
  mongo_db: # name of BD service
    image: mongo
    container_name: mongo_entrega_final
    ports:
      - 27017:27017
    volumes:
      - entrega_final:/data/configdb
      - entrega_final:/data/db
    restart: always

networks:
  nodejs-network:
    name: nodejs-network
    driver: bridge

volumes:
  entrega_final: